# Generated by Django 4.0.3 on 2022-03-25 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('submission_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('minutes', models.IntegerField()),
                ('date', models.DateField()),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='timesheets.timesheet')),
            ],
        ),
    ]
