# Generated by Django 4.0.3 on 2022-03-25 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('work', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('minutes', models.IntegerField()),
                ('date', models.DateField()),
                ('timesheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timesheets.timesheet')),
            ],
        ),
    ]
