# Generated by Django 4.0.3 on 2022-03-25 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheets', '0002_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='client',
        ),
        migrations.RemoveField(
            model_name='work',
            name='date',
        ),
        migrations.RemoveField(
            model_name='work',
            name='minutes',
        ),
        migrations.RemoveField(
            model_name='work',
            name='role',
        ),
        migrations.RemoveField(
            model_name='work',
            name='task',
        ),
        migrations.RemoveField(
            model_name='work',
            name='work',
        ),
        migrations.AlterField(
            model_name='work',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='timesheets.timesheet'),
        ),
    ]
